# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae36ea240922d37881edfecfe58e376f60b173a7191ecc55f99804ca12746cb9d3b9273ccd55f434fc3ddae9e9b88400112dc12e059da9b4c2ca53fc95ddfeb

test:
  secret_key_base: b1e5dfcd4adf667cf9179291a2632c1ee9bce75c2d7f2318809b5440682e2e4ef09bc25923fca5ada2a9d95213e6567eaf84b469f915d18edd55a106433d0390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
